#include <bits/stdc++.h>
#include <filesystem>
#include <unistd.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fstream>
#include <iostream>
#include "sha1.hpp"
#include <chrono>
#include <ctime>
#include <fcntl.h>
#include <termios.h>
#include <sys/sendfile.h>
#include <string.h>
#include <termios.h>
#include <dirent.h>
#include "mycolors.h"
using namespace std;
string cwd; 
